import rss from '@astrojs/rss';
import { getCollection } from 'astro:content';
import { SITE } from '../consts';
import { LOCALE_META } from '../i18n';

// English RSS feed. The Spanish feed is generated by /es/rss.xml.js and
// filters posts to lang='es' instead.
export async function GET(context) {
  const posts = (
    await getCollection('blog', ({ data }) => !data.draft && data.lang === 'en')
  ).sort((a, b) => b.data.pubDate.valueOf() - a.data.pubDate.valueOf());

  return rss({
    title: `${SITE.title} — Blog`,
    description: SITE.description,
    site: context.site ?? SITE.url,
    items: posts.map((post) => ({
      title: post.data.title,
      description: post.data.description,
      pubDate: post.data.pubDate,
      link: `/blog/${post.id}/`,
      categories: post.data.tags,
      author: SITE.author,
    })),
    customData: `<language>${LOCALE_META.en.rssLang}</language>`,
    stylesheet: false,
  });
}
